garage:
    resource: "@GarageBundle/Resources/config/routing.yml"
    prefix:   /garage/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"