car_index:
    path:     /
    defaults: { _controller: "GarageBundle:Car:index" }
    methods:  GET

car_own:
    path:     /mycars
    defaults: { _controller: "GarageBundle:Car:listOwn" }
    methods:  GET

car_show:
    path:     /{id}/show
    defaults: { _controller: "GarageBundle:Car:show" }
    methods:  GET

car_new:
    path:     /new
    defaults: { _controller: "GarageBundle:Car:new" }
    methods:  [GET, POST]

car_edit:
    path:     /{id}/edit
    defaults: { _controller: "GarageBundle:Car:edit" }
    methods:  [GET, POST]

car_delete:
    path:     /{id}/delete
    defaults: { _controller: "GarageBundle:Car:delete" }
    methods:  DELETE
